### ISSUE TITLE
关于配置

### ISSUE THREAD

**Issue by wltony** [sun0x00/redtorch#1]
SpringApplication will load properties from application.properties files in the following locations and add them to the Spring Environment:
[docs](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-application-property-files)
A /config subdirectory of the current directory.
The current directory
A classpath /config package
The classpath root

所以只要在当前运行目录下，创建config目录，app;ication,properties 或者直接放在当前目录下，可以覆盖classpath里的properties文件。 RtConfig.properties 需要改下加载程序，这样也可以符合springboot的约定。logback.xml  LOG_HOME无需指定盘符，会自动创建log目录。``

**Comment by sun0x00** [comment]
感谢提出建议！

1. RtConfig.properties会遵循SprintBoot约定，增加尝试使用war外部配置文件覆盖默认配置，会尽快提交相关代码

2. LOG_HOME主要是提供一个示例，有部分运维有指定log目录用于监控的需求
