### ISSUE TITLE
接口实现过于耦合

### ISSUE THREAD

**Issue by watano** [sun0x00/redtorch#11]
目前正在使用redTorch实现一个用于币圈的量化交易. 但是在实现过程中发现现有接口的耦合度太高了,很难定制实现自己的业务逻辑, 希望作者予以改进,谢谢. 
建议:
方案1: 直接使用spring的依赖注入方式实现接口与实现代码的绑定.
+ 在实现代码Impl类上使用@Component注解声明服务;
+ 在使用字段上使用@Autowired注解;
这样的好处是代码相对标准,但是过于依赖spring ioc. 造成RunBacktestingForStrategyBK类似的回测方法不能直接使用main方法,而只能使用spring boot的测试用例模式

方案2: 使用Factory模式创建一个工厂类,统一初始化各个接口的实现.

**Comment by watano** [comment]
![image](https://user-images.githubusercontent.com/730526/43005430-6d8ea942-8c65-11e8-9b2b-4b5826cb449d.png)

**Comment by sun0x00** [comment]
@watano 感谢提出相关的问题！
个人也比较认同你的看法，交易相关的部分耦合度有些高。最开始做这个平台的时候并非从Spring框架作为起始编写的，而是参考vnpy先写了策略管理、数据访问、接口和常规交易部分。因此目前平台是可以剥离Spring运行的，只是无法通过web访问相关功能。交易相关的这部分是我实盘在用的，因此没有想过要改，不过耦合过于紧密这确实是一个问题。你提出的两个方案我这两天会认真研究一下。如果有任何其他问题，欢迎使用QQ和我沟通,1055532121。Thanks!

**Comment by watano** [comment]
你的qq加不上,你加我wx吧? watanoo

**Comment by sun0x00** [comment]
@watano 我修改了QQ验证方式，应该可以了,原来的问题也是可以随便填的。。好多年没改过了

**Comment by sun0x00** [comment]
@watano 项目已经通过Spring实现了完全解耦，并通过gradle根据不同功能模块做了适当粒度的分拆,近期测试后会提交覆盖现有项目。

**Comment by watano** [comment]
very nice!
