### ISSUE TITLE
mac下System.load so文件报异常

### ISSUE THREAD

**Issue by ljackf** [sun0x00/redtorch#13]
java.lang.UnsatisfiedLinkError: /private/tmp/xyz/redtorch/api/jctp/lib/libthostmduserapi.so: dlopen(/private/tmp/xyz/redtorch/api/jctp/lib/libthostmduserapi.so, 1): no suitable image found.  Did find:
	/private/tmp/xyz/redtorch/api/jctp/lib/libthostmduserapi.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/private/tmp/xyz/redtorch/api/jctp/lib/libthostmduserapi.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00

**Comment by sun0x00** [comment]
libthostmduserapi.so和libthostmduserapi.so是上期技术的官方接口文件，我这里没有源码也无法修改。根据目前已经了解到的情况,应该不支持在Mac下运行。通过协议层面倒是可以在OS X下实现交易，但是由于政策法规原因，此代码将不会出现在这个开源项目中。
