### ISSUE TITLE
每次新加一个策略来实验，好麻烦

### ISSUE THREAD

**Issue by whitelilis** [sun0x00/redtorch#18]
能做成动态插入的形式就好了，技术上，还没太想好怎么实现。

**Comment by sun0x00** [comment]
@whitelilis 你这个问题我已经考虑了一个月了，就是我说的多进程拆分，不同的策略，运行在不同的jvm进程上，会好很多，主引擎不需要重启，方便调试。已经在测试了，这是个大变更，需要时间。

**Comment by mohuanzhen** [comment]
好

**Comment by sun0x00** [comment]
2019-01-06从dev分支合并至master分支的代码已经解决此问题。此问题将关闭，如有疑问请再次激活，谢谢。
