### ISSUE TITLE
有开发者问项目是否还在更新，在这里统一回答一下

### ISSUE THREAD

**Issue by sun0x00** [sun0x00/redtorch#19]
1.项目还在更新
2.接下来的变动比较大，会采用进程解耦，以便于提高策略调试效率
3.界面会重写，可能会降低刷新速率，比如从实时降低为500ms，但提高巨量数据下的稳定性，提高视觉效果和低分辨率兼容性
4.Gateway接口将会拆分为行情MD和交易TD
5.更新时间待定。。预计10月8日之前

**Comment by whitelilis** [comment]
先赞为敬

**Comment by ssh352** [comment]
非常期待新版本

**Comment by whitelilis** [comment]
还有 3 天，加油

**Comment by whitelilis** [comment]
跳票了。。。。。。加油

**Comment by sun0x00** [comment]
@whitelilis 最近simnow不稳定，测试不顺利，但仍在推进。

**Comment by sun0x00** [comment]
最新代码已更新至dev分支，待完全测试后将会merge到master分支
