### ISSUE TITLE
是否支持运行在mac下或者linux下

### ISSUE THREAD

**Issue by chuanjunxu** [sun0x00/redtorch#20]
是否支持运行在mac下或者linux下

**Comment by sun0x00** [comment]
框架本身为纯Java代码编写，因此能够运行在任何标准版本的JVM上，这些操作系统包括Windows Linux Mac。但需要特别关注的是接口部分，目前框架仅集成了CTP接口，但上期技术仅提供了linux和windows中的库文件，因此Mac不能支持CTP接口。如有其它接口接入，可自行编写。
