### ISSUE TITLE
最后一步保命的手段

### ISSUE THREAD

**Issue by whitelilis** [sun0x00/redtorch#23]
软件使用过程中总会有各种各样的异常，而做为最后一步保命的手段，我觉得“全部平掉”应该是一个一下就可以保命的东西。
然后没有这样一个命令，比如：

1. 账号有多个
1. 每个账号有多个持仓
1. 有多单有空单
1. 有需要“平今”的，有需要“平昨”的

所有的这些，都是程序擅长的事情，所以如果有一个“一键全平”的功能，可以在最关键的时候救一命，不然到时手忙脚乱，就不好搞了。

**Comment by sun0x00** [comment]
经过很久的考虑，这个操作权限太高，反而容易造成误操作，由于系统已经开放了相关API，决定不统一开发此功能。如有疑问请再次激活，谢谢。
