### ISSUE TITLE
可否考虑去掉对 mongo 的依赖

### ISSUE THREAD

**Issue by whitelilis** [sun0x00/redtorch#25]
mongo 对于 Tick 这种类似时间序列的存储貌似不是很高效呢。
如果要存上两年以上的数据，mongo 的性能可能会有问题。

**Comment by sun0x00** [comment]
Mongo暂时不会去掉，如果有需要可以自行改造。Mongo的性能问题主要来自内存不足。我自用的几台物理机内存没有低于64GB的，因此暂时没有遇到此类问题。
