### ISSUE TITLE
OnRspQryDepthMarketData 返回的结果中，好几个double类型都是无穷大

### ISSUE THREAD

**Issue by frank-4570428** [sun0x00/redtorch#4]
OnRspQryDepthMarketData 返回的结果中，好几个double类型都是无穷大，例如rb1810, 20180620的getClosePrice()就是无穷大，请是不是生成的dll文件有关。

**Comment by sun0x00** [comment]
这个问题我也关注到了，最近没来得及改，我在用的时候过滤了这部分数据，具体原因待查。

**Comment by sun0x00** [comment]
最近逆向分析研究了一下CTP底层协议，实现了一个自用的纯Java NIO版本，根据已知的情况判断，无穷大是正常的，主要是在一些字段没有有效数据的时候，采用1.7977e+308填充，例如涨跌停板、结算价未产生等特殊情况，官方没有使用0，主要是为了防止误判，需要自行判断。因此认为这是一个常量，和生成的dll无关。

**Comment by frank-4570428** [comment]
谢谢，我还有个疑问，为何在JAVA里面不能将创建连接等一系列放到一个单独的线程中执行呢。这样我就可以在一个程序里面同时处理多个账户的信息了。
可是当我使用单独的线程处理每个账号时，程序直接就挂掉了。
