### ISSUE TITLE
TradingEngineServiceImpl.java ZeusEngineService.java 的cancelOrder函数签名容易误解

### ISSUE THREAD

**Issue by ssh352** [sun0x00/redtorch#40]
<img width="778" alt="screen shot 2018-11-27 at 5 29 02 pm" src="https://user-images.githubusercontent.com/41779116/49071928-050d1a00-f26a-11e8-8865-1e88e03927cc.png">

TradingEngineServiceImpl implements ZeusEngineService ,这两个class都有cancelOrder

    void cancelOrder(String originalOrderID) ;
    void cancelOrder(String rtOrderID);

一个传递的是rtOrderID 另一个传递的是originalOrderID 这两个是完全不一样的两个ID

能否改一改 让其一致 避免用户传递错误的参数？

**Comment by sun0x00** [comment]
2019-01-06从dev分支合并至master分支的代码已经解决此问题。此问题将关闭，如有疑问请再次激活，谢谢。
