### ISSUE TITLE
VUE挺好的呀，为何又换成了React了呢

### ISSUE THREAD

**Issue by Atlaschu** [sun0x00/redtorch#48]

**Comment by sun0x00** [comment]
主要是vue写在一个page时，太多数据时性能下降过于严重，对高频监控来说简直是噩梦，而且组件也没有React多。下一步计划在web页面保留的同时做一个桌面级客户端，当然，还是React来写，但是有更大的性能空间，可以分屏等等

**Comment by sun0x00** [comment]
暂时保留此问题。
