### ISSUE TITLE
在CtpGateway中一个可能的问题

### ISSUE THREAD

**Issue by yellow013** [sun0x00/redtorch#50]
在CtpGateway.class中，有这样一个TimerTask：
`class QueryTimerTask extends TimerTask{

	    @Override
	    public void run() {
	    	try {
		    	if(isConnected()) {
			        queryAccount();
		    	}
			    Thread.sleep(1250);
			    if(isConnected()) {
				    queryPosition();
			    }
			    Thread.sleep(1250);
	    	}catch (Exception e) {
				log.error(gatewayLogInfo+"定时查询发生异常",e);
			}
	    }
	}
`
这个定时任务的执行，仅仅休眠就有2500ms，没有加上执行查询的耗时。
而这个任务执行的间隔仅仅1000ms：
`timer.schedule(new QueryTimerTask(), new Date(), 1000);`
这会导致任务队列大量堆积，不知这是一个问题，还是特意如此设计？
能否请作者解答一下？

**Comment by sun0x00** [comment]
这是一个关于CTP流控的问题。定时查询持仓和账户需要分别进行，且均受制于流控。除非持仓数量巨大，否则这个等待时间是合适的，即便是异步返回未能在1250ms内完成，也会在下一次流控解除时继续查询到结果。

**Comment by yellow013** [comment]
@sun0x00 是我看错了，我以为你用了scheduleAtFixedRate
