### ISSUE TITLE
📢准备弃用Ant Design前端框架，改为Microsoft Office UI Fabric

### ISSUE THREAD

**Issue by sun0x00** [sun0x00/redtorch#55]
在过去的一段事件中很多朋友反映操作界面不够友好，无论是交互逻辑还是视觉感受，经过一段时间的总结，目前认为主要有两个方面原因，一是Ant Design字号过大，界面空间利用率不足，二是局限于单个html页面。除此之外，dva的开发模式过于复杂，学习成本太高，函数命名混乱，不利于推广和二次开发。因此接下来考虑采用MobX替换Dva,使用Microsoft Office UI Fabric统一UI样式开发Web App。同时推进使用Electron开发的统一样式的支持多窗口的Desktop App。

**Comment by ssh352** [comment]
这样就只能在windows上运行前端了吧？

**Comment by sun0x00** [comment]
@ssh352 仍然可以跨平台

**Comment by ssh352** [comment]
那你🐂 希望能够一直跨平台，辛苦了！

**Comment by pontali** [comment]
Microsoft Office UI Fabric 会不会学习成本更高？

**Comment by windli93** [comment]
@sun0x00 是否可以改为vue，vue的界面操作又好，开发也简单。

**Comment by sun0x00** [comment]
代码已经重构，相关文件已经重新整理。
