### ISSUE TITLE
请教RedTorch的运行机制

### ISSUE THREAD

**Issue by kevinhuangwl** [sun0x00/redtorch#57]
如果我没理解错的话，CTP接口的订阅都需要有一个“容器”维护MdSpi与TdSpi对象的生命周期，而从源码我看到RedTorch用CtpGateway来维护，但却找不到是什么来维护CtpGateway对象。可否补充说明一下？

**Comment by sun0x00** [comment]
@kevinhuangwl  在CoreEngine中使用反射创建相关Gateway实例
