### ISSUE TITLE
关于FastEvent的设计与使用困惑

### ISSUE THREAD

**Issue by kevinhuangwl** [sun0x00/redtorch#58]
在GatewayAbstract的代码中看到FastEvent的event与eventType用的都是一样的值，那么event与eventType的区别是什么呢？为什么要设计两个字段呢？

**Comment by sun0x00** [comment]
早期有些场景并非完全一致，例如，同样一个类型为Order的事件，可能会有event=Order的事件，也有可能再产生一个evnet=Order+orderID 的事件，用于不同场景的判断。
