### ISSUE TITLE
关于CTP帐号登录问题

### ISSUE THREAD

**Issue by mchuangzhong** [sun0x00/redtorch#68]
在项目正常启动后，通过web页面添加一个网关后点击连接，假如此时所填写的密码错误，目前项目会一直在循环的进行登录，CTP返回 交易接口登录回报错误 错误ID:3,错误信息:CTP:不合法的登录 ，最终会出现 交易接口登录回报错误 错误ID:75,错误信息:CTP:连续登录失败次数超限，登录被禁止  。
是否可以做个登录失败次数的限制，请问这个问题如何解决，谢谢！

**Comment by sun0x00** [comment]
@mchuangzhong  这个问题应该写到README中，开发调试的时候发现了这个问题，所以自己使用的时候比较谨慎小心，登录信息一直都是复制粘贴多次检查。可以考虑在slave中加入配置版本登录错误记录，假设登录错误，新增回调接口，拒绝反复登录，直到新版本配置登录成功。

**Comment by mchuangzhong** [comment]
CTP这块我也是新手，刚已经有个帐号被限制登录了，还请大神赐教这个问题具体该怎么修改。另外一个问题就是期货有不同交易时间段，一些期货公司的前置服务器会在非交易时间段关闭，那么如何保证CTP的自动连接。

**Comment by sun0x00** [comment]
@mchuangzhong  当前程序就是不断地尝试重连，直到连接成功。重连失败分两种情况，第一种是连接超时，第二种是连接回报一些特定错误，都会触发断开重连。

**Comment by xiaopinwei** [comment]
X-Quant重连这一点做的非常爽，请借鉴一下。

**Comment by sun0x00** [comment]
@xiaopinwei 具体指哪方面

**Comment by xiaopinwei** [comment]
谢谢大佬回复，已成功运行项目，十分便利。不知道你有没有用过X-Quant，研究它一下，有助于你的项目借鉴完善。
