### ISSUE TITLE
导入项目所出现的几个问题

### ISSUE THREAD

**Issue by xiaopinwei** [sun0x00/redtorch#69]
导入项目，启动不了，提示如下：
2019-08-24 16:23:37.266 [main                ] [WARN ] jsr >>> UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used 

我是win7操作系统，按照GitHub文档步骤安装，
1，安装MongoDB
2，安装vs2013x64运行库
3，安装JDK11 x64并设置环境变量（JAVA_HOME=C:\Java\jdk-11.0.2 ,PATH=%JAVA_HOME%\bin）
4，eclipse-jee-2019-06-R-win32-x86_64.zip
在Eclipse中使用File->Import->Existing Gradle Projects导入本项目
5，通过rt-node-master中的RtNodeMasterApplication.java启动主节点
启动主节点卡在这个问题，请不吝指教，那里步骤有问题，如何顺利项目运行？谢谢

再次run一下，提示如下：

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.1.5.RELEASE)

2019-08-24 16:34:32.423 [main                ] [WARN ] jsr >>> UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used 
2019-08-24 16:34:33.777 [main                ] [ERROR] LoggingFailureAnalysisReporter >>> 

***************************
APPLICATION FAILED TO START
***************************

Description:

Web server failed to start. Port 9099 was already in use.

Action:

Identify and stop the process that's listening on port 9099 or configure this application to listen on another port.
 
![image](https://user-images.githubusercontent.com/40836918/63634818-34807400-c68e-11e9-8a76-87c5d4d8a819.png)

**Comment by sun0x00** [comment]
第一次启动后是警告，配置不生效，可以暂且忽略。直接访问9099端口接口
第二次是因为你第一次已经启动成功了，所以自然9099端口被占用，无法再次启动
