### ISSUE TITLE
最新版本使用websocket替换了原来的socket其中除了通用性之外还有什么好处吗?

### ISSUE THREAD

**Issue by dsadsaad** [sun0x00/redtorch#71]
请教一下E神,最新版本使用websocket替换了原来的socket其中除了通用性之外还有什么好处吗?

**Comment by sun0x00** [comment]
@dsadsaad 通用性更强，底层更加可控。原来用socket.io，虽然功能上看似强大，但数据交互过程中总是包着一层JSON，兼容WebSocket的其他协议也不会被用到，而且socket.io没有其他语言对应的客户端，所以替换成了标准WebSocket。
