### ISSUE TITLE
增加使用文档Wiki

### ISSUE THREAD

**Issue by windli93** [sun0x00/redtorch#73]
本人是业余手动交易者，以交易美股为主，主业是Java后台开发，把楼主的开源项目下了下来，一通操作总算把项目运行起来了。之后看了楼主的项目框架整合和设计，原生的Netty + Disruptor, 整个项目的设计是很厉害的，本来最近打算学习Python去使用vn.py做量化，比较了下，Java其实对高频交易的支撑是非常优秀的，老虎还有盈透都有Java Api放出来，完全不用愁外部的交易接口。以下是我的问题整理：

1. 现在我的主要问题是，没有使用文档，看着空空的前端页面不知道去干什么，自己去折腾需要太多的时间，所以希望能增加说明文档。
2.  解决Idea无法及时获取静态文件的问题     
![图片](https://user-images.githubusercontent.com/16792321/65488983-ccb38800-dedc-11e9-8226-19a8af0b76d2.png)
3. 目前Spring boot 和 Idea 兼容没有问题，我已经运行起来了。
![图片](https://user-images.githubusercontent.com/16792321/65489125-18fec800-dedd-11e9-9092-ed9dc3ec6851.png)
4  Master节点启动总是报错，显示是验证登录信息异常
![图片](https://user-images.githubusercontent.com/16792321/65489261-59f6dc80-dedd-11e9-90dd-6963a9863fd7.png)

**Comment by LanShengHong** [comment]
遇到同样的问题，不知道你有没有解决？

**Comment by MrHat365** [comment]
需要在启动Master节点之后访问对应的地址127.0.0.1:9099的管理后台设置对应的节点。
![图片](https://user-images.githubusercontent.com/13407096/67270381-295d8f00-f4eb-11e9-9b5c-539633fedb61.png)
复制节点的编号和对应的ID设置到Slave的配置文件中，application.properties。
rt.rpc.client.node-id=10002
rt.rpc.client.token=a19c0069-7e76-4902-b603-4dd931bbe4fa
中。
启动RtNodeSlaveApplication即可。
