### ISSUE TITLE
📢更新预告

### ISSUE THREAD

**Issue by sun0x00** [sun0x00/redtorch#74]
即将发布新的版本，做了大量修改，请谨慎更新

+ 删除已经过时的旧版本CTP接口
+ 增强了子节点的稳定性，非交易事件因CTP接口导致的闪退问题得到了修复（稳定性待持续考察）
+ 修改了部分协议结构，进一步增强多节点接入的性能（仍然在一定程度上牺牲了传输时效,也不会太差）
+ 加入rt-desktop模块，此模块为桌面客户端
+ 其它

以上更新已经实盘使用一月有余，仍在做细节上的微调，近期更新

**Comment by shitoupai** [comment]
这个什么时候发布呢？

**Comment by sun0x00** [comment]
已更新
