### ISSUE TITLE
登录成功后，右上角一直提示警告: 服务器关闭或Token已过期，请尝试刷新页面登录

### ISSUE THREAD

**Issue by xiciliu** [sun0x00/redtorch#8]
登录成功后，右上角一直提示警告: 服务器关闭或Token已过期，请尝试刷新页面登录

**Comment by sun0x00** [comment]
@xiciliu 
9098、9099端口是否能正常访问？
能否提供一些其它信息，例如浏览器厂商、版本，以及服务端是否有任何形式的异常信息

**Comment by sun0x00** [comment]
需要更多附加信息，暂时关闭此问题。
