### ISSUE TITLE
OrderStatusEnum 数值有误

### ISSUE THREAD

**Issue by fireinjava** [sun0x00/redtorch#85]
// OrderStatusEnum是一个报单状态类型
enum class OrderStatusEnum(val value: Int) {

    AllTraded("0"), // 全部成交
    PartTradedQueueing("1"), // 部分成交还在队列中
    PartTradedNotQueueing("2"), // 部分成交不在队列中
    NoTradeQueueing("3"), // 未成交还在队列中
    NoTradeNotQueueing("4"), // 未成交不在队列中
    Canceled(“5”), // 撤单
    Unkown(“a”), // 未知
    NotTouched(“b"), // 尚未触发
    Touched("c") // 已触发
    //Rejected(9) // 已拒绝
}

**Comment by LudanLink** [comment]
您好，邮件已收到。我将尽快给您回复，谢谢。

**Comment by sun0x00** [comment]
感谢反馈，但未能寻获问题中所示错误代码，暂时关闭此问题。

**Comment by LudanLink** [comment]
您好，邮件已收到。我将尽快给您回复，谢谢。
