### ISSUE TITLE
rt-gateway-ctp工程resource下缺少6v6v9版本的so文件

### ISSUE THREAD

**Issue by lebin** [sun0x00/redtorch#87]
缺少以下so文件：
/assembly/jctpv6v6v9cpx64api/libthostmduserapi_se.so
/assembly/jctpv6v6v9x64api/libthostmduserapi_se.so

**Comment by sun0x00** [comment]
libthostmduserapi_se.so和libthostmduserapi_se.so是上期技术提供的，可以直接在上期技术网站下载6.6.9版本的接口，且命名可能需要自行修改，加前缀lib。（请注意区分生产版与评测版）

另外，还缺少封装so，由于不同发行版的Linux中编译的封装so并不能100%兼容，所以没有编译，可以参考以下链接编译，源码与windows一致，都是swig生成，引入jni头文件的部分请根据实际路径修改。 https://github.com/sun0x00/jctpapi-linux
